import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
export const ROOT = path.join(__dirname, '..');

// In cloud environments (Railway, Render, Fly.io), set ARCADE_DB_PATH to a
// persistent volume path (e.g. /data/mollys-arcade.db). Locally, DB lives
// next to the project root as usual.
const DATA_BASE = process.env.ARCADE_DATA_DIR || ROOT;

export const CONFIG = {
    PORT: process.env.PORT || 3000,
    ROOT,
    DB_PATH: process.env.ARCADE_DB_PATH || path.join(DATA_BASE, 'mollys-arcade.db'),
    ROMS_DIR: process.env.ARCADE_ROMS_DIR || path.join(ROOT, 'roms'),
    ARTWORK_DIR: process.env.ARCADE_ARTWORK_DIR || path.join(ROOT, 'artwork'),
    DATA_DIR: path.join(ROOT, 'data'),
    SAVES_DIR: process.env.ARCADE_SAVES_DIR || path.join(ROOT, 'saves'),
    EMULATORJS_CDN: 'https://cdn.emulatorjs.org/stable/data',
    LIBRETRO_THUMBS: 'https://thumbnails.libretro.com',
    ARCHIVE_ORG_API: 'https://archive.org/advancedsearch.php',
    MAMEDEV_ROMS_URL: 'https://www.mamedev.org/roms/',
    METADATA_FETCH_DELAY: 100,
};

export const SYSTEMS = [
    {
        id: 'dreamcast',
        name: 'Sega Dreamcast',
        short_name: 'DC',
        core: 'flycast',
        extensions: ['.cdi', '.gdi', '.chd', '.cue'],
        libretro_dir: 'Sega - Dreamcast',
        bios: ['dc_boot.bin'],
        color: '#FF6B35',
        sort_order: 15,
    },
    {
        id: 'nes',
        name: 'Nintendo Entertainment System',
        short_name: 'NES',
        core: 'fceumm',
        extensions: ['.nes', '.unf', '.fds'],
        libretro_dir: 'Nintendo - Nintendo Entertainment System',
        bios: [],
        color: '#CE1124',
        sort_order: 1,
    },
    {
        id: 'snes',
        name: 'Super Nintendo',
        short_name: 'SNES',
        core: 'snes9x',
        extensions: ['.sfc', '.smc', '.swc'],
        libretro_dir: 'Nintendo - Super Nintendo Entertainment System',
        bios: [],
        color: '#7B2D8E',
        sort_order: 2,
    },
    {
        id: 'gba',
        name: 'Game Boy Advance',
        short_name: 'GBA',
        core: 'mgba',
        extensions: ['.gba'],
        libretro_dir: 'Nintendo - Game Boy Advance',
        bios: [],
        color: '#4A00A0',
        sort_order: 6,
    },
    {
        id: 'genesis',
        name: 'Sega Genesis / Mega Drive',
        short_name: 'Genesis',
        core: 'genesis_plus_gx',
        extensions: ['.md', '.gen', '.smd'],
        libretro_dir: 'Sega - Mega Drive - Genesis',
        bios: [],
        color: '#171717',
        sort_order: 10,
    },
    {
        id: 'gamegear',
        name: 'Sega Game Gear',
        short_name: 'GG',
        core: 'genesis_plus_gx',
        extensions: ['.gg'],
        libretro_dir: 'Sega - Game Gear',
        bios: [],
        color: '#222222',
        sort_order: 12,
    },
    {
        id: 'saturn',
        name: 'Sega Saturn',
        short_name: 'Saturn',
        core: 'yabause',
        extensions: ['.cue', '.iso', '.chd'],
        libretro_dir: 'Sega - Saturn',
        bios: ['saturn_bios.bin'],
        color: '#003DA5',
        sort_order: 13,
    },
    {
        id: '32x',
        name: 'Sega 32X',
        short_name: '32X',
        core: 'picodrive',
        extensions: ['.32x'],
        libretro_dir: 'Sega - 32X',
        bios: [],
        color: '#333333',
        sort_order: 14,
    },
    {
        id: 'psx',
        name: 'PlayStation',
        short_name: 'PS1',
        core: 'pcsx_rearmed',
        extensions: ['.bin', '.cue', '.img', '.iso', '.pbp', '.chd'],
        libretro_dir: 'Sony - PlayStation',
        bios: ['scph1001.bin'],
        color: '#00439C',
        sort_order: 20,
    },
    {
        id: 'atari2600',
        name: 'Atari 2600',
        short_name: '2600',
        core: 'stella2014',
        extensions: ['.a26'],
        libretro_dir: 'Atari - 2600',
        bios: [],
        color: '#D35400',
        sort_order: 30,
    },
    {
        id: 'atari7800',
        name: 'Atari 7800',
        short_name: '7800',
        core: 'prosystem',
        extensions: ['.a78'],
        libretro_dir: 'Atari - 7800',
        bios: [],
        color: '#E67E22',
        sort_order: 31,
    },
    {
        id: 'jaguar',
        name: 'Atari Jaguar',
        short_name: 'Jaguar',
        core: 'virtualjaguar',
        extensions: ['.j64', '.jag'],
        libretro_dir: 'Atari - Jaguar',
        bios: [],
        color: '#CC0000',
        sort_order: 32,
    },
    {
        id: 'lynx',
        name: 'Atari Lynx',
        short_name: 'Lynx',
        core: 'handy',
        extensions: ['.lnx'],
        libretro_dir: 'Atari - Lynx',
        bios: ['lynxboot.img'],
        color: '#555555',
        sort_order: 33,
    },
    {
        id: 'tg16',
        name: 'TurboGrafx-16 / PC Engine',
        short_name: 'TG16',
        core: 'mednafen_pce',
        extensions: ['.pce', '.cue', '.ccd'],
        libretro_dir: 'NEC - PC Engine - TurboGrafx 16',
        bios: ['syscard3.pce'],
        color: '#FF6600',
        sort_order: 40,
    },
    {
        id: 'neogeo',
        name: 'Neo Geo',
        short_name: 'Neo Geo',
        core: 'fbneo',
        extensions: ['.zip'],
        libretro_dir: 'SNK - Neo Geo',
        bios: ['neogeo.zip'],
        color: '#D4A017',
        sort_order: 41,
    },
    {
        id: 'ngp',
        name: 'Neo Geo Pocket',
        short_name: 'NGP',
        core: 'mednafen_ngp',
        extensions: ['.ngp', '.ngc'],
        libretro_dir: 'SNK - Neo Geo Pocket',
        bios: [],
        color: '#003399',
        sort_order: 42,
    },
    {
        id: 'arcade',
        name: 'Arcade (MAME)',
        short_name: 'Arcade',
        core: 'mame2003_plus',
        extensions: ['.zip'],
        libretro_dir: 'MAME',
        bios: [],
        color: '#FFD700',
        sort_order: 50,
    },
    {
        id: 'fbneo',
        name: 'Arcade (FBNeo)',
        short_name: 'FBNeo',
        core: 'fbneo',
        extensions: ['.zip'],
        libretro_dir: 'FBNeo - Arcade Games',
        bios: [],
        color: '#FF4444',
        sort_order: 51,
    },
    {
        id: 'wonderswan',
        name: 'WonderSwan',
        short_name: 'WS',
        core: 'mednafen_wswan',
        extensions: ['.ws', '.wsc'],
        libretro_dir: 'Bandai - WonderSwan',
        bios: [],
        color: '#2196F3',
        sort_order: 60,
    },
    {
        id: 'vb',
        name: 'Virtual Boy',
        short_name: 'VB',
        core: 'beetle_vb',
        extensions: ['.vb', '.vboy'],
        libretro_dir: 'Nintendo - Virtual Boy',
        bios: [],
        color: '#CC0000',
        sort_order: 61,
    },

    // ── Desktop Mode: Native Emulator Systems ────────────────────────────────
    {
        id: 'gamecube',
        name: 'Nintendo GameCube',
        short_name: 'GCN',
        core: 'native',
        extensions: ['.iso', '.gcm', '.gcz', '.ciso', '.rvz'],
        libretro_dir: 'Nintendo - GameCube',
        bios: [],
        color: '#7B2D8E',
        sort_order: 3,
    },
    {
        id: 'wii',
        name: 'Nintendo Wii',
        short_name: 'Wii',
        core: 'native',
        extensions: ['.iso', '.wbfs', '.gcz', '.ciso', '.rvz'],
        libretro_dir: 'Nintendo - Wii',
        bios: [],
        color: '#C0C0C0',
        sort_order: 4,
    },
    {
        id: 'wiiu',
        name: 'Nintendo Wii U',
        short_name: 'WiiU',
        core: 'native',
        extensions: ['.wud', '.wux', '.iso', '.rpx'],
        libretro_dir: 'Nintendo - Wii U',
        bios: [],
        color: '#009AC7',
        sort_order: 5,
    },
    {
        id: 'switch',
        name: 'Nintendo Switch',
        short_name: 'NSW',
        core: 'native',
        extensions: ['.xci', '.nsp', '.nca'],
        libretro_dir: 'Nintendo - Switch',
        bios: [],
        color: '#E60012',
        sort_order: 9,
    },
    {
        id: 'ps2',
        name: 'PlayStation 2',
        short_name: 'PS2',
        core: 'native',
        extensions: ['.iso', '.bin', '.img', '.chd'],
        libretro_dir: 'Sony - PlayStation 2',
        bios: ['SCPH10000.BIN'],
        color: '#00308F',
        sort_order: 21,
    },
    {
        id: 'ps3',
        name: 'PlayStation 3',
        short_name: 'PS3',
        core: 'native',
        extensions: ['.iso', '.pkg'],
        libretro_dir: 'Sony - PlayStation 3',
        bios: [],
        color: '#00439C',
        sort_order: 22,
    },
    {
        id: 'xbox',
        name: 'Xbox',
        short_name: 'Xbox',
        core: 'native',
        extensions: ['.iso', '.xbe'],
        libretro_dir: 'Microsoft - Xbox',
        bios: ['mcpx_1.0.bin', 'Complex_4627.bin'],
        color: '#107C10',
        sort_order: 23,
    },
];

// Extension → system lookup (built at import time)
export const EXT_TO_SYSTEM = new Map();
for (const sys of SYSTEMS) {
    for (const ext of sys.extensions) {
        // Some extensions are shared — first system wins, folder hints override
        if (!EXT_TO_SYSTEM.has(ext)) {
            EXT_TO_SYSTEM.set(ext, sys.id);
        }
    }
}

// Folder name → system lookup
export const FOLDER_HINTS = new Map([
    ['nes', 'nes'], ['famicom', 'nes'], ['nintendo', 'nes'],
    ['snes', 'snes'], ['super nintendo', 'snes'], ['super famicom', 'snes'],
    ['gba', 'gba'], ['gameboy advance', 'gba'], ['game boy advance', 'gba'],
    ['genesis', 'genesis'], ['megadrive', 'genesis'], ['mega drive', 'genesis'], ['sega genesis', 'genesis'],
    ['gamegear', 'gamegear'], ['game gear', 'gamegear'], ['gg', 'gamegear'],
    ['saturn', 'saturn'], ['sega saturn', 'saturn'],
    ['dreamcast', 'dreamcast'], ['sega dreamcast', 'dreamcast'], ['dc', 'dreamcast'],
    ['32x', '32x'], ['sega 32x', '32x'],
    ['psx', 'psx'], ['ps1', 'psx'], ['playstation', 'psx'],
    ['atari2600', 'atari2600'], ['atari 2600', 'atari2600'],
    ['atari7800', 'atari7800'], ['atari 7800', 'atari7800'],
    ['jaguar', 'jaguar'], ['atari jaguar', 'jaguar'],
    ['lynx', 'lynx'], ['atari lynx', 'lynx'],
    ['tg16', 'tg16'], ['turbografx', 'tg16'], ['turbografx-16', 'tg16'], ['pc engine', 'tg16'], ['pce', 'tg16'],
    ['neogeo', 'neogeo'], ['neo geo', 'neogeo'], ['neo-geo', 'neogeo'], ['aes', 'neogeo'], ['mvs', 'neogeo'],
    ['ngp', 'ngp'], ['neo geo pocket', 'ngp'], ['neogeo pocket', 'ngp'],
    ['arcade', 'arcade'], ['mame', 'arcade'],
    ['fbneo', 'fbneo'], ['fba', 'fbneo'],
    ['wonderswan', 'wonderswan'], ['ws', 'wonderswan'],
    ['virtualboy', 'vb'], ['virtual boy', 'vb'],
    // Native systems
    ['gamecube', 'gamecube'], ['gcn', 'gamecube'], ['gc', 'gamecube'], ['nintendo gamecube', 'gamecube'],
    ['wii', 'wii'], ['nintendo wii', 'wii'],
    ['wiiu', 'wiiu'], ['wii u', 'wiiu'], ['nintendo wii u', 'wiiu'],
    ['switch', 'switch'], ['nsw', 'switch'], ['nintendo switch', 'switch'],
    ['ps2', 'ps2'], ['playstation 2', 'ps2'], ['playstation2', 'ps2'],
    ['ps3', 'ps3'], ['playstation 3', 'ps3'], ['playstation3', 'ps3'],
    ['xbox', 'xbox'], ['xbox original', 'xbox'], ['microsoft xbox', 'xbox'],
    ['xbox360', 'xbox360'], ['xbox 360', 'xbox360'], ['x360', 'xbox360'], ['microsoft xbox 360', 'xbox360'],
]);
