import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
export const ROOT = path.join(__dirname, '..');

// In cloud environments (Railway, Render, Fly.io), set ARCADE_DB_PATH to a
// persistent volume path (e.g. /data/mollys-arcade.db). Locally, DB lives
// next to the project root as usual.
const DATA_BASE = process.env.ARCADE_DATA_DIR || ROOT;

export const CONFIG = {
    PORT: process.env.PORT || 3000,
    ROOT,
    DB_PATH: process.env.ARCADE_DB_PATH || path.join(DATA_BASE, 'mollys-arcade.db'),
    ROMS_DIR: process.env.ARCADE_ROMS_DIR || path.join(ROOT, 'roms'),
    ARTWORK_DIR: process.env.ARCADE_ARTWORK_DIR || path.join(ROOT, 'artwork'),
    DATA_DIR: path.join(ROOT, 'data'),
    SAVES_DIR: process.env.ARCADE_SAVES_DIR || path.join(ROOT, 'saves'),
    EMULATORJS_CDN: 'https://cdn.emulatorjs.org/stable/data',
    LIBRETRO_THUMBS: 'https://thumbnails.libretro.com',
    ARCHIVE_ORG_API: 'https://archive.org/advancedsearch.php',
    MAMEDEV_ROMS_URL: 'https://www.mamedev.org/roms/',
    METADATA_FETCH_DELAY: 100,

    // Metadata enrichment APIs
    DATS_DIR: path.join(ROOT, 'data', 'dats'),
    SCREENSCRAPER_API: 'https://api.screenscraper.fr/api2',
    IGDB_API: 'https://api.igdb.com/v4',
    TWITCH_AUTH_URL: 'https://id.twitch.tv/oauth2/token',
    RETROACHIEVEMENTS_API: 'https://retroachievements.org/API',
};

// ScreenScraper system ID mapping (our system_id → SS systemeid)
export const SS_SYSTEM_MAP = {
    nes: 3, snes: 4, gba: 12, genesis: 1, gamegear: 21, saturn: 22,
    dreamcast: 23, '32x': 19, psx: 57, atari2600: 26, atari7800: 41,
    jaguar: 27, lynx: 28, tg16: 31, neogeo: 142, ngp: 25, arcade: 75,
    fbneo: 75, wonderswan: 45, vb: 11,
};

// IGDB platform ID mapping (our system_id → IGDB platform)
export const IGDB_PLATFORM_MAP = {
    nes: 18, snes: 19, gba: 24, genesis: 29, gamegear: 35, saturn: 32,
    dreamcast: 23, '32x': 30, psx: 7, atari2600: 59, atari7800: 60,
    jaguar: 62, lynx: 61, tg16: 86, neogeo: 80, ngp: 119, arcade: 52,
    fbneo: 52, wonderswan: 57, vb: 87,
};

export const SYSTEMS = [
    {
        id: 'dreamcast',
        name: 'Sega Dreamcast',
        short_name: 'DC',
        core: 'flycast',
        extensions: ['.cdi', '.gdi', '.chd', '.cue'],
        libretro_dir: 'Sega - Dreamcast',
        bios: ['dc_boot.bin'],
        color: '#FF6B35',
        sort_order: 15,
    },
    {
        id: 'nes',
        name: 'Nintendo Entertainment System',
        short_name: 'NES',
        core: 'fceumm',
        extensions: ['.nes', '.unf', '.fds'],
        libretro_dir: 'Nintendo - Nintendo Entertainment System',
        bios: [],
        color: '#CE1124',
        sort_order: 1,
    },
    {
        id: 'snes',
        name: 'Super Nintendo',
        short_name: 'SNES',
        core: 'snes9x',
        extensions: ['.sfc', '.smc', '.swc'],
        libretro_dir: 'Nintendo - Super Nintendo Entertainment System',
        bios: [],
        color: '#7B2D8E',
        sort_order: 2,
    },
    {
        id: 'gba',
        name: 'Game Boy Advance',
        short_name: 'GBA',
        core: 'mgba',
        extensions: ['.gba'],
        libretro_dir: 'Nintendo - Game Boy Advance',
        bios: [],
        color: '#4A00A0',
        sort_order: 6,
    },
    {
        id: 'genesis',
        name: 'Sega Genesis / Mega Drive',
        short_name: 'Genesis',
        core: 'genesis_plus_gx',
        extensions: ['.md', '.gen', '.smd'],
        libretro_dir: 'Sega - Mega Drive - Genesis',
        bios: [],
        color: '#171717',
        sort_order: 10,
    },
    {
        id: 'gamegear',
        name: 'Sega Game Gear',
        short_name: 'GG',
        core: 'genesis_plus_gx',
        extensions: ['.gg'],
        libretro_dir: 'Sega - Game Gear',
        bios: [],
        color: '#222222',
        sort_order: 12,
    },
    {
        id: 'saturn',
        name: 'Sega Saturn',
        short_name: 'Saturn',
        core: 'yabause',
        extensions: ['.cue', '.iso', '.chd'],
        libretro_dir: 'Sega - Saturn',
        bios: ['saturn_bios.bin'],
        color: '#003DA5',
        sort_order: 13,
    },
    {
        id: '32x',
        name: 'Sega 32X',
        short_name: '32X',
        core: 'picodrive',
        extensions: ['.32x'],
        libretro_dir: 'Sega - 32X',
        bios: [],
        color: '#333333',
        sort_order: 14,
    },
    {
        id: 'psx',
        name: 'PlayStation',
        short_name: 'PS1',
        core: 'pcsx_rearmed',
        extensions: ['.bin', '.cue', '.img', '.iso', '.pbp', '.chd'],
        libretro_dir: 'Sony - PlayStation',
        bios: ['scph1001.bin'],
        color: '#00439C',
        sort_order: 20,
    },
    {
        id: 'atari2600',
        name: 'Atari 2600',
        short_name: '2600',
        core: 'stella2014',
        extensions: ['.a26'],
        libretro_dir: 'Atari - 2600',
        bios: [],
        color: '#D35400',
        sort_order: 30,
    },
    {
        id: 'atari7800',
        name: 'Atari 7800',
        short_name: '7800',
        core: 'prosystem',
        extensions: ['.a78'],
        libretro_dir: 'Atari - 7800',
        bios: [],
        color: '#E67E22',
        sort_order: 31,
    },
    {
        id: 'jaguar',
        name: 'Atari Jaguar',
        short_name: 'Jaguar',
        core: 'virtualjaguar',
        extensions: ['.j64', '.jag'],
        libretro_dir: 'Atari - Jaguar',
        bios: [],
        color: '#CC0000',
        sort_order: 32,
    },
    {
        id: 'lynx',
        name: 'Atari Lynx',
        short_name: 'Lynx',
        core: 'handy',
        extensions: ['.lnx'],
        libretro_dir: 'Atari - Lynx',
        bios: ['lynxboot.img'],
        color: '#555555',
        sort_order: 33,
    },
    {
        id: 'tg16',
        name: 'TurboGrafx-16 / PC Engine',
        short_name: 'TG16',
        core: 'mednafen_pce',
        extensions: ['.pce', '.cue', '.ccd'],
        libretro_dir: 'NEC - PC Engine - TurboGrafx 16',
        bios: ['syscard3.pce'],
        color: '#FF6600',
        sort_order: 40,
    },
    {
        id: 'neogeo',
        name: 'Neo Geo',
        short_name: 'Neo Geo',
        core: 'fbneo',
        extensions: ['.zip'],
        libretro_dir: 'SNK - Neo Geo',
        bios: ['neogeo.zip'],
        color: '#D4A017',
        sort_order: 41,
    },
    {
        id: 'ngp',
        name: 'Neo Geo Pocket',
        short_name: 'NGP',
        core: 'mednafen_ngp',
        extensions: ['.ngp', '.ngc'],
        libretro_dir: 'SNK - Neo Geo Pocket',
        bios: [],
        color: '#003399',
        sort_order: 42,
    },
    {
        id: 'arcade',
        name: 'Arcade (MAME)',
        short_name: 'Arcade',
        core: 'mame2003_plus',
        extensions: ['.zip'],
        libretro_dir: 'MAME',
        bios: [],
        color: '#FFD700',
        sort_order: 50,
    },
    {
        id: 'fbneo',
        name: 'Arcade (FBNeo)',
        short_name: 'FBNeo',
        core: 'fbneo',
        extensions: ['.zip'],
        libretro_dir: 'FBNeo - Arcade Games',
        bios: [],
        color: '#FF4444',
        sort_order: 51,
    },
    {
        id: 'wonderswan',
        name: 'WonderSwan',
        short_name: 'WS',
        core: 'mednafen_wswan',
        extensions: ['.ws', '.wsc'],
        libretro_dir: 'Bandai - WonderSwan',
        bios: [],
        color: '#2196F3',
        sort_order: 60,
    },
    {
        id: 'vb',
        name: 'Virtual Boy',
        short_name: 'VB',
        core: 'beetle_vb',
        extensions: ['.vb', '.vboy'],
        libretro_dir: 'Nintendo - Virtual Boy',
        bios: [],
        color: '#CC0000',
        sort_order: 61,
    },
    {
        id: 'gb',
        name: 'Game Boy',
        short_name: 'GB',
        core: 'gambatte',
        extensions: ['.gb'],
        libretro_dir: 'Nintendo - Game Boy',
        bios: [],
        color: '#8B956D',
        sort_order: 7,
    },
    {
        id: 'gbc',
        name: 'Game Boy Color',
        short_name: 'GBC',
        core: 'gambatte',
        extensions: ['.gbc'],
        libretro_dir: 'Nintendo - Game Boy Color',
        bios: [],
        color: '#6A0DAD',
        sort_order: 8,
    },
    {
        id: 'sms',
        name: 'Sega Master System',
        short_name: 'SMS',
        core: 'genesis_plus_gx',
        extensions: ['.sms'],
        libretro_dir: 'Sega - Master System - Mark III',
        bios: [],
        color: '#CC0000',
        sort_order: 11,
    },
    {
        id: 'n64',
        name: 'Nintendo 64',
        short_name: 'N64',
        core: 'mupen64plus_next',
        extensions: ['.z64', '.n64', '.v64'],
        libretro_dir: 'Nintendo - Nintendo 64',
        bios: [],
        color: '#009900',
        sort_order: 3,
    },
    {
        id: 'nds',
        name: 'Nintendo DS',
        short_name: 'NDS',
        core: 'melonds',
        extensions: ['.nds'],
        libretro_dir: 'Nintendo - Nintendo DS',
        bios: ['bios7.bin', 'bios9.bin', 'firmware.bin'],
        color: '#A0A0A0',
        sort_order: 9,
    },
    {
        id: 'psp',
        name: 'PlayStation Portable',
        short_name: 'PSP',
        core: 'ppsspp',
        extensions: ['.iso', '.cso', '.pbp'],
        libretro_dir: 'Sony - PlayStation Portable',
        bios: [],
        color: '#000000',
        sort_order: 22,
    },
];

// Extension → system lookup (built at import time)
export const EXT_TO_SYSTEM = new Map();
for (const sys of SYSTEMS) {
    for (const ext of sys.extensions) {
        // Some extensions are shared — first system wins, folder hints override
        if (!EXT_TO_SYSTEM.has(ext)) {
            EXT_TO_SYSTEM.set(ext, sys.id);
        }
    }
}

// Folder name → system lookup
export const FOLDER_HINTS = new Map([
    ['nes', 'nes'], ['famicom', 'nes'], ['nintendo', 'nes'],
    ['snes', 'snes'], ['super nintendo', 'snes'], ['super famicom', 'snes'],
    ['gba', 'gba'], ['gameboy advance', 'gba'], ['game boy advance', 'gba'],
    ['genesis', 'genesis'], ['megadrive', 'genesis'], ['mega drive', 'genesis'], ['sega genesis', 'genesis'],
    ['gamegear', 'gamegear'], ['game gear', 'gamegear'], ['gg', 'gamegear'],
    ['saturn', 'saturn'], ['sega saturn', 'saturn'],
    ['dreamcast', 'dreamcast'], ['sega dreamcast', 'dreamcast'], ['dc', 'dreamcast'],
    ['32x', '32x'], ['sega 32x', '32x'],
    ['psx', 'psx'], ['ps1', 'psx'], ['playstation', 'psx'],
    ['atari2600', 'atari2600'], ['atari 2600', 'atari2600'],
    ['atari7800', 'atari7800'], ['atari 7800', 'atari7800'],
    ['jaguar', 'jaguar'], ['atari jaguar', 'jaguar'],
    ['lynx', 'lynx'], ['atari lynx', 'lynx'],
    ['tg16', 'tg16'], ['turbografx', 'tg16'], ['turbografx-16', 'tg16'], ['pc engine', 'tg16'], ['pce', 'tg16'],
    ['neogeo', 'neogeo'], ['neo geo', 'neogeo'], ['neo-geo', 'neogeo'], ['aes', 'neogeo'], ['mvs', 'neogeo'],
    ['ngp', 'ngp'], ['neo geo pocket', 'ngp'], ['neogeo pocket', 'ngp'],
    ['arcade', 'arcade'], ['mame', 'arcade'],
    ['fbneo', 'fbneo'], ['fba', 'fbneo'],
    ['wonderswan', 'wonderswan'], ['ws', 'wonderswan'],
    ['virtualboy', 'vb'], ['virtual boy', 'vb'],
    ['gb', 'gb'], ['gameboy', 'gb'], ['game boy', 'gb'],
    ['gbc', 'gbc'], ['gameboy color', 'gbc'], ['game boy color', 'gbc'],
    ['sms', 'sms'], ['master system', 'sms'], ['sega master system', 'sms'],
    ['n64', 'n64'], ['nintendo 64', 'n64'], ['nintendo64', 'n64'],
    ['nds', 'nds'], ['nintendo ds', 'nds'], ['ds', 'nds'],
    ['psp', 'psp'], ['playstation portable', 'psp'],
]);

